# Postgres Database (Catalog)
postgres:
  container_name: bareos-postgres
  image: sameersbn/postgresql:9.4-19
  environment:
    - "DB_USER=bareos"
    - "DB_PASS=bareos"
  volumes:
    - "./_data/pstgres:/var/lib/postgresql"

# Bareos Storage Daemon
bareos-sd:
  container_name: bareos-sd
  image: shoifele/bareos-sd
  ports:
    - "9103:9103"
  volumes:
    - "./_data/etc:/etc/bareos"
    - "./_data/storage:/storage"

# Bareos Director
bareos-dir:
  container_name: bareos-dir
  image: shoifele/bareos-dir
  environment:
    - "DB_PASS=bareos"
  volumes:
    - "./_data/etc:/etc/bareos"
  links:
    - postgres
    - bareos-sd

# Bareos WebUI
bareos-ui:
  container_name: bareos-ui
  image: shoifele/bareos-ui
  links:
    - bareos-dir
  ports:
    - "80:80"
