# Postgres Database (Catalog)
postgres:
  container_name: bareos-postgres
  image: sameersbn/postgresql:9.4-19
  environment:
    - "DB_USER=bareos"
    - "DB_PASS=bareos"
  volumes:
    - "/data/pstgres:/var/lib/postgresql"

# Bareos Storage Daemon
bareos-sd:
  container_name: bareos-sd
  image: shoifele/bareos-sd
  ports:
    - "9103:9103"
  volumes:
    - "/data/etc:/etc/bareos"
    - "/data/storage:/storage"

bareos-fd:
  container_name: bareos-fd
  image: djeshkov/bareos-fd
  ports:
    - "9102:9102"

  volumes:
    - "/data/etc:/etc/bareos"
    - /:/mnt:ro
  links:
    - bareos-dir


# Bareos Director
bareos-dir:
  container_name: bareos-dir
  image: djeshkov/bareos-dir
  environment:
    - "DB_PASS=bareos"
  volumes:
    - "/data/etc:/etc/bareos"
  links:
    - postgres
    - bareos-sd

# Bareos WebUI
bareos-ui:
  container_name: bareos-ui
  image: shoifele/bareos-ui
  links:
    - bareos-dir
  ports:
    - "8000:80"
